### ISSUE TITLE
Export

### ISSUE THREAD

**Issue by karthikb351** [paulgb/tweetvis#1]
Is there a way to export/publish a tree once you've generated it? It would be a nice to have a portable version I could share.

**Comment by paulgb** [comment]
Hi Karthik,

It may be too late for you, but there is now! I made it into a Chrome
extension which lets it do a lot more things, including a downloadable
link. It's here if you're interested:
https://chrome.google.com/webstore/detail/treeverse/aahmjdadniahaicebomlagekkcnlcila?hl=en-US

Cheers,

-- Paul

**Comment by karthikb351** [comment]
Sweet. I'll use the chrome extension and the new repo :)
